name: lst-school-2022-01
channels:
  - conda-forge
  - default
dependencies:
  - python=3.8
  - numpy=1.21
  - astropy~=4.2
  - pip
  - ctapipe~=0.11
  - gammapy=0.18
  - h5py
  - ipython
  - jupyter
  - matplotlib=3.4
  - notebook
  - joblib
  - toml
  - protozfits=2.0
  - pyparsing=2.4
  - sphinx~=4.2
  - sphinx-automodapi
  - sphinx_rtd_theme
  - sphinx-argparse
  - nbsphinx
  - numpydoc
  - traitlets=5.0
  - pandas
  - pymongo
  - seaborn
  - ipympl
  - vitables
  - pip:
      - ctapipe_io_lst~=0.13.2
      - ctaplot~=0.5.5 
      - pyirf~=0.5.0
      - lstchain==0.8.4
      - lstmcpipe==0.5.1
