mc_allowed_tels:
    LST-1: 1
    MAGIC-I: 2
    MAGIC-II : 3


LST:

    # The following settings are derived from lstchain v0.8.4:
    # - lstchain_standard_config.json
    # - lstchain/data/lstchain_dl1ab_tune_MC_to_Crab_config.json

    image_extractor:
        name: 'LocalPeakWindowSum'
        window_shift: 4
        window_width: 8

    increase_nsb:
        use: true
        extra_noise_in_dim_pixels: 1.2
        extra_bias_in_dim_pixels: 0.5
        transition_charge: 8
        extra_noise_in_bright_pixels: 1.2

    increase_psf:
        use: true
        smeared_light_fraction: 0.125

    tailcuts_clean:
        picture_thresh: 8
        boundary_thresh: 4
        keep_isolated_pixels: false
        min_number_picture_neighbors: 2

    time_delta_cleaning:
        use: true
        min_number_neighbors: 1
        time_limit: 2

    dynamic_cleaning:
        use: true
        threshold: 267
        fraction: 0.03

    use_only_main_island: false


MAGIC:
    image_extractor:
        name: 'LocalPeakWindowSum'
        window_shift: 2
        window_width: 5

    magic_clean:
        picture_thresh: 6
        boundary_thresh: 3.5
        max_time_off: 7.38
        max_time_diff: 2.46
        usetime: true
        usesum: true

    bad_pixels:
        pedestalLevel: 400
        pedestalLevelVariance: 4.5
        pedestalType: 'FromExtractorRndm'


event_coincidence:
    type_lst_time: 'dragon_time'
    window_width: 6.0e-7      # unit: [sec]
    offset_start: -5.0e-6     # unit: [sec]
    offset_stop: 0.0          # unit: [sec]


stereo_reco:
    quality_cuts: '(intensity > 50) & (width > 0)'


energy_regressor:
    settings:
        n_estimators: 150
        criterion: "squared_error"
        max_depth: 50
        min_samples_split: 2
        min_samples_leaf: 2
        min_weight_fraction_leaf: 0.0
        max_features: "auto"
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        bootstrap: true
        oob_score: false
        n_jobs: 5
        random_state: 42
        verbose: 0
        warm_start: false
        ccp_alpha: 0.0
        max_samples: null

    features: [
        'intensity',
        'length',
        'width',
        'skewness',
        'kurtosis',
        'slope',
        'intensity_width_2',
        'h_max',
        'impact'
    ]


direction_regressor:
    settings:
        n_estimators: 150
        criterion: "squared_error"
        max_depth: 50
        min_samples_split: 2
        min_samples_leaf: 2
        min_weight_fraction_leaf: 0.0
        max_features: "auto"
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        bootstrap: true
        oob_score: false
        n_jobs: 5
        random_state: 42
        verbose: 0
        warm_start: false
        ccp_alpha: 0.0
        max_samples: null

    features: [
        'intensity',
        'length',
        'width',
        'skewness',
        'kurtosis',
        'slope',
        'intensity_width_2',
        'h_max',
        'impact'
    ]


event_classifier:
    settings:
        n_estimators: 100
        criterion: "gini"
        max_depth: 100
        min_samples_split: 2
        min_samples_leaf: 2
        min_weight_fraction_leaf: 0.0
        max_features: "auto"
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        bootstrap: true
        oob_score: false
        n_jobs: 5
        random_state: 42
        verbose: 0.0
        warm_start: false
        class_weight: null
        ccp_alpha: 0.0
        max_samples: null

    features: [
        'intensity',
        'length',
        'width',
        'skewness',
        'kurtosis',
        'slope',
        'intensity_width_2',
        'h_max',
        'impact'
    ]
